### ISSUE TITLE
ImportError: _eval_pysur

### ISSUE THREAD

**Issue by atogw** [vijayvarma392/surfinBH#22]
I installed surfinBH (version 1.2.2) using pip. Now I want to load surfinBH but get an import error related to '_eval_pysur'.

### Installation:
`pip install surfinBH`

### Code and Error:
`>>> import surfinBH`
`Traceback (most recent call last):`
 ` File "<stdin>", line 1, in <module>`
`  File "/home/jandro/.local/lib/python3.6/site-packages/surfinBH/__init__.py", line 1, in <module>`
`    from . import surfinBH`
`  File "/home/jandro/.local/lib/python3.6/site-packages/surfinBH/surfinBH.py", line 37, in <module>`
`    from . import _eval_pysur`
`ImportError: cannot import name '_eval_pysur'`

**Comment by duetosymmetry** [comment]
Yes, this is indeed a bug with our pypi upload. We will increment the patch level number and upload a new version (@vijayvarma392 you're the only one that can do this, right?) that includes eval_pysur.

If you need a fix before Vijay gets around to it, please clone the git repo, including the submodule for eval_pysur.

**Comment by vijayvarma392** [comment]
Should now be fixed in version 1.2.3 https://pypi.org/project/surfinBH/.
